name: Draft Release Approval

on:
  release:
    types: [published]
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      driver:
        description: "Driver to build"
        required: true
      version:
        description: "Version to release"
        required: true

jobs:
  build_all_drivers:
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master') || github.event_name == 'pull_request'
    name: Build and Release Drivers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        driver: [mongodb, mysql, postgres] # Add new drivers here as they become available
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: github.com/d-cryptic/olake/.github/workflows/build-and-release-driver.yml
        with:
          driver: ${{ github.event.inputs.driver || matrix.driver }}
          version: ${{ github.event.inputs.version || github.event.release.tag_name }}
          secrets: inherit